import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { execSync } from "node:child_process";
import { JsonRpcProvider, Wallet, HDNodeWallet, ContractFactory } from "ethers";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..");

const TEST_MNEMONIC =
  "test test test test test test test test test test test junk";

// NOTE: ethers v6 dropped the path argument from Wallet.fromPhrase; use
// HDNodeWallet.fromPhrase(mnemonic, password, path) to derive non-default
// accounts deterministically.
const accountAt = (index) =>
  HDNodeWallet.fromPhrase(TEST_MNEMONIC, "", `m/44'/60'/0'/0/${index}`);

const DEPLOYER_PRIVATE_KEY = accountAt(0).privateKey;
const GUARDIAN_ADDRESS = accountAt(1).address;
const BENEFICIARY_ADDRESS = accountAt(2).address;

const RPC_URL = process.env.ANVIL_RPC_URL || "http://localhost:8545";
const CHAIN_ID = Number(process.env.E2E_CHAIN_ID || 43113);
const CHAIN_NAME = "Avalanche Fuji Testnet";

function loadArtifact() {
  const artifactPath = resolve(
    repoRoot,
    "artifacts/contracts/SpooVault.sol/SpooVault.json"
  );
  if (!existsSync(artifactPath)) {
    console.log("[deploy-anvil] Hardhat artifact missing, compiling...");
    execSync("npx hardhat compile --config hardhat.config.cjs", {
      cwd: repoRoot,
      stdio: "inherit",
    });
  }
  return JSON.parse(readFileSync(artifactPath, "utf8"));
}

async function main() {
  const artifact = loadArtifact();
  const provider = new JsonRpcProvider(RPC_URL);
  const deployer = new Wallet(DEPLOYER_PRIVATE_KEY, provider);

  console.log(
    `[deploy-anvil] Deploying SpooVault to ${RPC_URL} (chainId ${CHAIN_ID})`
  );
  console.log(`[deploy-anvil] Deployer: ${deployer.address}`);

  const factory = new ContractFactory(
    artifact.abi,
    artifact.bytecode,
    deployer
  );
  const contract = await factory.deploy();
  await contract.waitForDeployment();
  const address = await contract.getAddress();

  console.log(`[deploy-anvil] SpooVault deployed at ${address}`);

  const outDir = resolve(repoRoot, "e2e");
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  const env = [
    `# Generated by e2e/scripts/deploy-anvil.mjs — do not edit by hand.`,
    `VITE_CONTRACT_ADDRESS=${address}`,
    `VITE_AVALANCHE_RPC=${RPC_URL}`,
    `VITE_CHAIN_ID=${CHAIN_ID}`,
    `VITE_CHAIN_NAME=${CHAIN_NAME}`,
    `VITE_CONTRACT_DEPLOY_BLOCK=0`,
    `VITE_TX_WAIT_TIMEOUT_MS=180000`,
    `VITE_STELLAR_CONTRACT_ADDRESS=`,
    `# Test accounts (Anvil dev mnemonic) — exposed for the contract-level E2E.`,
    `E2E_GUARDIAN_ADDRESS=${GUARDIAN_ADDRESS}`,
    `E2E_BENEFICIARY_ADDRESS=${BENEFICIARY_ADDRESS}`,
    "",
  ].join("\n");

  writeFileSync(resolve(outDir, ".env.e2e"), env);
  console.log(`[deploy-anvil] Wrote e2e/.env.e2e`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
